name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20  # Use the version of Go you're working with

    - name: Install dependencies
      run: go mod tidy

    - name: Build the project
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...

    - name: Run the application
      run: go run main.go

